const intro = [
    'Rob broke some devastating news to me! He had an encounter with someone shortly before he left Australia. This person, who will remain unnamed, had a curse that was passed on to Rob one fateful night. Death began following him, attempting to destroy him through its phantom assassins. Believing that relocating overseas would relieve him of these assassins and potentially the curse, Rob moved to San Francisco to build a new life. Shortly after moving to SF, Rob and I met. Believing the risk was no longer there, in due course, he passed this fateful curse on to me.',
    'For the last two years, the two of us have been living peacefully and without incident. Unfortunately, a few days ago, Rob spotted one of the phantom assassins in downtown SF creepily making its way toward Alameda! It must have boarded a boat in Australia and made its way to the States! Beware that these assassins don\'t just follow...they can <i>wander</i> all over the world! Hence, we have no choice but to preserve both of our safety by getting as far away from the Bay Area as possible. Since Thailand has incredible beaches, delicious food, and is nearly halfway around the world, Rob and I have chosen to move there for now. We are hoping this distance will grant us time to strategize and formulate a plan against the phantom assassins. Rest assured, we are doing everything in our power to remain safe and figure out how to beat these evil creatures. For now, we will be <i>wandering</i> around the world as much as necessary to stay ahead of this thing.',
    'Please visit our website again for regular updates on our location and status. We will also be sharing any new information we discover about this horrid curse and its <i>wandering</i> phantom assassins!'
];

module.exports = {
  intro
};
